### PR TITLE
feat: Add Home Page Component and Integrate with /home-page Route (#25)

### PR DESCRIPTION
**Pull request by ussyalfaks**

### CODE REVIEW

**Review by Ugo-X — CHANGES_REQUESTED** [review]
text color is not what is in the design file

**Comment by ussyalfaks** [comment]
I’ve updated the text color to match the design file using the specified HEX code.

**Comment by Ugo-X** [comment]
> I’ve updated the text color to match the design file using the specified HEX code.

Screenshot 2024-12-21 at 23 38 25
you did not update all of them

**Comment by ussyalfaks** [comment]
I’ve updated the text color to match the design file using the specified HEX code.

**Comment by Ugo-X** [comment]
Screenshot 2024-12-22 at 08 14 25

**Comment by Ugo-X** [comment]
not fixed. please look through your design and fix everything so i can merge

**Review by Ugo-X — APPROVED** [review]

**Pull request merged**
